version: 1.0.{build}
image: Visual Studio 2017
install:
  - docker version
branches:
  only:
  - master
init:
  # Good practice, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
build_script:
  - ps: ./scripts/build.ps1

deploy_script:
- ps: ./scripts/deploy.ps1